---
blank_issues_enabled: false
issue_templates:
  - name: "ğŸ› Bug Report"
    description: "Report a bug in the system."
    title: "[ğŸ› Bug]: "
    labels: ["bug"]
    body: "./ISSUE_TEMPLATE/bug_report.md"
  - name: "ğŸš€ Feature Request"
    description: "Propose a new feature or improvement."
    title: "[ğŸš€ Feature]: "
    labels: ["enhancement"]
    body: "./ISSUE_TEMPLATE/feature_request.md"
  - name: "ğŸ“š Documentation"
    description: "Suggest updates or additions to the documentation."
    title: "[ğŸ“š Docs]: "
    labels: ["documentation"]
    body: "./ISSUE_TEMPLATE/documentation.md"
